# Basic
title: è¿·äºæ˜Ÿé™…è¿·èˆª
subtitle: æ’­å®¢
description: ä¸€æ¡£é€‚åˆæ˜Ÿé™…æ—…è¡Œæ”¶å¬çš„èŠå¤©èŠ‚ç›®
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: è¿·äºæ˜Ÿé™…è¿·èˆª
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ä¸­æ–‡æ˜Ÿé™…è¿·èˆªæ’­å®¢
url: "http://wqjkdqj.github.io"

# Comment
#comment:
#    # disqus: leopard
#    duoshuo: leopard 

# Social
social:
    weibo: lostinst
    github: wqjkdqj
    # twitter: 
    mail: subspacesignal@qq.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
# baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰èŠ‚ç›®, description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘ä»¬, description: about, url: '/about'}      
    

# Pagination
#gems: [jekyll-paginate,jekyll-sitemap]
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
# for the 4000 is used
# port: 4444
